export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const PURCHASE_BURGER = 'PURCHASE_BURGER';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_LOADING = 'PURCHASE_BURGER_LOADING';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_LOADING = 'FETCH_ORDERS_LOADING';

export const DELETE_ORDER = 'DELETE_ORDER';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCES = 'AUTH_SUCCES';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SAVE_INGREDIENTS = 'SAVE_INGREDIENTS'
